; about.asm — 8trax 4K intro
; x86-64 Linux, NASM, dynamic linking against libX11/libGL/libGLX/libz/libasound/libpthread
;
; Stack alignment convention:
;   `_start` does `sub rsp, 8` so every function we CALL enters with rsp%16 == 0.
;   Functions that make further calls need no additional alignment fixup — unless
;   they push an odd number of extra stack arguments before a call (see x11_open).

    bits 64

; ── X11 ────────────────────────────────────────────────────────────────────────
    extern XOpenDisplay
    extern XDefaultScreen
    extern XDefaultRootWindow
    extern XCreateSimpleWindow
    extern XSelectInput
    extern XMapWindow
    extern XMoveWindow
    extern XInternAtom
    extern XChangeProperty
    extern XNextEvent
    extern XPending
    extern XLookupKeysym
    extern XCloseDisplay

; ── GLX ────────────────────────────────────────────────────────────────────────
    extern glXChooseVisual
    extern glXCreateContext
    extern glXMakeCurrent
    extern glXSwapBuffers
    extern glXGetProcAddress

; ── zlib ───────────────────────────────────────────────────────────────────────
    extern uncompress

; ── ALSA ───────────────────────────────────────────────────────────────────────
    extern snd_pcm_open
    extern snd_pcm_hw_params_malloc
    extern snd_pcm_hw_params_any
    extern snd_pcm_hw_params_set_access
    extern snd_pcm_hw_params_set_format
    extern snd_pcm_hw_params_set_rate_near
    extern snd_pcm_hw_params_set_channels
    extern snd_pcm_hw_params
    extern snd_pcm_writei

; ── OpenGL ─────────────────────────────────────────────────────────────────────
    extern glClear
    extern glClearColor
    extern glViewport
    extern glDrawArrays
    extern glCreateShader
    extern glShaderSource
    extern glCompileShader
    extern glCreateProgram
    extern glAttachShader
    extern glLinkProgram
    extern glUseProgram
    extern glGetUniformLocation
    extern glUniform1f
    extern glUniform2f
    extern glGenTextures
    extern glBindTexture
    extern glTexImage2D
    extern glTexParameteri
    extern glPixelStorei

; ── pthreads ───────────────────────────────────────────────────────────────────
    extern pthread_create

    global _start

; ── window geometry ────────────────────────────────────────────────────────────
WIN_W   equ 800
WIN_H   equ 600

; ── X11 event / mask constants ─────────────────────────────────────────────────
KeyPressMask        equ (1 << 0)
StructureNotifyMask equ (1 << 17)
KeyPress            equ 2
ConfigureNotify     equ 22
DestroyNotify       equ 17
XK_Escape           equ 0xff1b

; ── ALSA constants ─────────────────────────────────────────────────────────────
SND_PCM_STREAM_PLAYBACK       equ 0
SND_PCM_ACCESS_RW_INTERLEAVED equ 3
SND_PCM_FORMAT_S16_LE         equ 2
SAMPLE_RATE                   equ 44100

; ── OpenGL constants ───────────────────────────────────────────────────────────
GL_COLOR_BUFFER_BIT equ 0x00004000
GL_FRAGMENT_SHADER  equ 0x8B30
GL_VERTEX_SHADER    equ 0x8B31
GL_TRIANGLES        equ 4
GL_TEXTURE_2D       equ 0x0DE1
GL_UNPACK_ALIGNMENT equ 0x0CF5
GL_TEXTURE_MAG_FILTER equ 0x2800
GL_TEXTURE_MIN_FILTER equ 0x2801
GL_LINEAR           equ 0x2601
GL_TEXTURE_WRAP_S   equ 0x2802
GL_TEXTURE_WRAP_T   equ 0x2803
GL_CLAMP_TO_EDGE    equ 0x812F
GL_R8               equ 0x8229
GL_RED              equ 0x1903
GL_UNSIGNED_BYTE    equ 0x1401

; ── timing ─────────────────────────────────────────────────────────────────────
CLOCK_MONOTONIC     equ 1
SYS_CLOCK_GETTIME   equ 228

; ── GLX visual attribute list (terminated by None = 0) ─────────────────────────
; GLX_RGBA=4, GLX_DOUBLEBUFFER=5 are boolean flags (key only, no value).
; Remaining entries are key/value pairs.
%define GLX_RGBA            4
%define GLX_DOUBLEBUFFER    5
%define GLX_RED_SIZE        8
%define GLX_GREEN_SIZE      9
%define GLX_BLUE_SIZE       10

; ───────────────────────────────────────────────────────────────────────────────
section .rodata

; Compressed shader source — generated by: make shader_blob.inc
; Symbols defined: shader_blob_srclen (uncompressed), shader_blob_zlen, shader_blob
%include "shader_blob.inc"

; Compressed SDF text atlas — generated by: make text_blob.inc
; Symbols defined: text_atlas_w, text_atlas_h, text_blob_zlen, text_blob
%include "text_blob.inc"

; Full-screen triangle via gl_VertexID — no VBO needed.
; i=0→(-1,-1), i=1→(3,-1), i=2→(-1,3); GPU clips to viewport.
sz_vert_src:
    db "#version 330 core", 10
    db "void main(){int i=gl_VertexID;", 10
    db "vec2 p=vec2(float((i<<1)&2),float(i&2));", 10
    db "gl_Position=vec4(p*2.0-1.0,0.0,1.0);}", 0

sz_iTime        db "iTime", 0
sz_iResolution  db "iResolution", 0
sz_wm_class     db "about", 0, "About", 0   ; WM_CLASS: instance=about, class=About

align 4
f_ns_inv        dd 1.0e-9       ; nanoseconds → seconds conversion factor
f_one           dd 1.0          ; alpha=1.0 for glClearColor

; ───────────────────────────────────────────────────────────────────────────────
section .data

sz_display  db ":0", 0
sz_pcm      db "default", 0

glx_attr    dd GLX_RGBA, GLX_DOUBLEBUFFER
            dd GLX_RED_SIZE,   8
            dd GLX_GREEN_SIZE, 8
            dd GLX_BLUE_SIZE,  8
            dd 0                    ; None

; ───────────────────────────────────────────────────────────────────────────────
section .bss

display     resq 1              ; Display*
screen      resd 1              ; int
root        resq 1              ; Window  (root)
window      resq 1              ; Window  (ours)
glx_ctx     resq 1              ; GLXContext
vis_info    resq 1              ; XVisualInfo*
shader_prog resd 1              ; GLuint
time_loc    resd 1              ; GLint — iTime uniform location
res_loc     resd 1              ; GLint — iResolution uniform location
pcm_handle  resq 1              ; snd_pcm_t*
audio_tid   resq 1              ; pthread_t
xevent      resb 192            ; XEvent  (large enough for all subtypes)
text_tex    resd 1              ; GLuint — SDF text atlas texture
decomp_buf  resb (512 * 1024)   ; zlib scratch: shader source, then text atlas
decomp_len  resq 1              ; decompressed byte count (for glShaderSource)
vert_shader resd 1              ; GLuint — vertex shader object
frag_shader resd 1              ; GLuint — fragment shader object
src_ptr     resq 1              ; glShaderSource needs char** — holds the char*
start_sec   resq 1              ; clock_gettime start: tv_sec
start_nsec  resq 1              ; clock_gettime start: tv_nsec
cur_ts      resb 16             ; struct timespec — updated each frame

; ───────────────────────────────────────────────────────────────────────────────
section .text

; ── entry point ────────────────────────────────────────────────────────────────
_start:
    ; sub rsp, 8 shifts the stack so that every subsequent `call` delivers
    ; the callee with rsp%16 == 0 — the alignment library code expects.
    ; _start never returns; we exit via sys_exit.
    sub     rsp, 8

    call    x11_open
    call    glx_init
    call    shader_init
    call    text_init
    call    audio_start
    call    event_loop

; ── x11_open ───────────────────────────────────────────────────────────────────
x11_open:
    ; XOpenDisplay(":0")
    lea     rdi, [rel sz_display]
    call    XOpenDisplay
    mov     [rel display], rax

    ; XDefaultScreen(display)
    mov     rdi, rax
    call    XDefaultScreen
    mov     [rel screen], eax

    ; XDefaultRootWindow(display)
    mov     rdi, [rel display]
    call    XDefaultRootWindow
    mov     [rel root], rax

    ; XCreateSimpleWindow(display, root, 0, 0, WIN_W, WIN_H, 0, 0, 0)
    ; Args 7-9 (border_width, border, background) go on the stack.
    ; Three qword pushes = 24 bytes; add one pad qword → 32 bytes total,
    ; keeping rsp 16-byte aligned before the call.
    mov     rdi, [rel display]
    mov     rsi, [rel root]
    xor     edx, edx            ; x = 0
    xor     ecx, ecx            ; y = 0
    mov     r8d, WIN_W
    mov     r9d, WIN_H
    sub     rsp, 8              ; alignment pad
    push    qword 0             ; background  (arg 9)
    push    qword 0             ; border      (arg 8)
    push    qword 0             ; border_width (arg 7)
    call    XCreateSimpleWindow
    add     rsp, 32
    mov     [rel window], rax

    ; XSelectInput(display, window, KeyPressMask | StructureNotifyMask)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    mov     edx, KeyPressMask | StructureNotifyMask
    call    XSelectInput

    ; XChangeProperty — set WM_CLASS so the WM can match this window in rules.
    ; XA_WM_CLASS=67, XA_STRING=31, PropModeReplace=0 are predefined protocol constants.
    ; Args 7-8 go on the stack; two qword pushes keep rsp 16-byte aligned.
    push    qword 12                    ; nelements: "about\0About\0" = 12 bytes (arg 8)
    lea     rax, [rel sz_wm_class]
    push    rax                         ; data pointer (arg 7)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    mov     edx, 67                     ; XA_WM_CLASS
    mov     ecx, 31                     ; XA_STRING
    mov     r8d, 8                      ; format: 8 bits per element
    xor     r9d, r9d                    ; PropModeReplace = 0
    call    XChangeProperty
    add     rsp, 16

    ; TODO: suppress window decorations (_MOTIF_WM_HINTS or _NET_WM_WINDOW_TYPE_SPLASH)
    ; TODO: XMoveWindow to centre on screen after mapping

    ; XMapWindow(display, window)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    call    XMapWindow

    ret

; ── glx_init ───────────────────────────────────────────────────────────────────
glx_init:
    ; glXChooseVisual(display, screen, glx_attr)
    mov     rdi, [rel display]
    mov     esi, [rel screen]
    lea     rdx, [rel glx_attr]
    call    glXChooseVisual
    mov     [rel vis_info], rax

    ; glXCreateContext(display, vis_info, NULL, True)
    mov     rdi, [rel display]
    mov     rsi, [rel vis_info]
    xor     edx, edx            ; share_list = NULL
    mov     ecx, 1              ; direct = True
    call    glXCreateContext
    mov     [rel glx_ctx], rax

    ; glXMakeCurrent(display, window, ctx)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    mov     rdx, [rel glx_ctx]
    call    glXMakeCurrent

    ret

; ── shader_init ────────────────────────────────────────────────────────────────
shader_init:
    ; Opaque black clear colour — avoids transparent artefacts with compositors
    ; when the shader hasn't painted yet (first frames, alt-tab, etc.)
    xorps   xmm0, xmm0
    xorps   xmm1, xmm1
    xorps   xmm2, xmm2
    movss   xmm3, [rel f_one]
    call    glClearColor

    ; uncompress(decomp_buf, &decomp_len, shader_blob, shader_blob_zlen)
    ; decomp_len carries the destination buffer capacity on entry;
    ; zlib overwrites it with the actual decompressed byte count on return.
    mov     qword [rel decomp_len], 512*1024
    lea     rdi, [rel decomp_buf]
    lea     rsi, [rel decomp_len]
    lea     rdx, [rel shader_blob]
    mov     ecx, shader_blob_zlen
    call    uncompress

    ; null-terminate so glShaderSource can accept length=NULL
    mov     rax, [rel decomp_len]
    lea     rcx, [rel decomp_buf]
    mov     byte [rcx + rax], 0

    ; glViewport(0, 0, WIN_W, WIN_H)
    xor     edi, edi
    xor     esi, esi
    mov     edx, WIN_W
    mov     ecx, WIN_H
    call    glViewport

    ; ── compile vertex shader ─────────────────────────────────────────────────
    mov     edi, GL_VERTEX_SHADER
    call    glCreateShader
    mov     [rel vert_shader], eax

    lea     rax, [rel sz_vert_src]
    mov     [rel src_ptr], rax          ; src_ptr = &sz_vert_src
    mov     edi, [rel vert_shader]
    mov     esi, 1
    lea     rdx, [rel src_ptr]          ; string** arg
    xor     ecx, ecx                    ; lengths = NULL → null-terminated
    call    glShaderSource

    mov     edi, [rel vert_shader]
    call    glCompileShader

    ; ── compile fragment shader ───────────────────────────────────────────────
    mov     edi, GL_FRAGMENT_SHADER
    call    glCreateShader
    mov     [rel frag_shader], eax

    lea     rax, [rel decomp_buf]
    mov     [rel src_ptr], rax          ; src_ptr = &decomp_buf
    mov     edi, [rel frag_shader]
    mov     esi, 1
    lea     rdx, [rel src_ptr]
    xor     ecx, ecx
    call    glShaderSource

    mov     edi, [rel frag_shader]
    call    glCompileShader

    ; ── link program ──────────────────────────────────────────────────────────
    call    glCreateProgram
    mov     [rel shader_prog], eax

    mov     edi, [rel shader_prog]
    mov     esi, [rel vert_shader]
    call    glAttachShader

    mov     edi, [rel shader_prog]
    mov     esi, [rel frag_shader]
    call    glAttachShader

    mov     edi, [rel shader_prog]
    call    glLinkProgram

    mov     edi, [rel shader_prog]
    call    glUseProgram

    ; ── cache uniform locations ───────────────────────────────────────────────
    mov     edi, [rel shader_prog]
    lea     rsi, [rel sz_iTime]
    call    glGetUniformLocation
    mov     [rel time_loc], eax

    mov     edi, [rel shader_prog]
    lea     rsi, [rel sz_iResolution]
    call    glGetUniformLocation
    mov     [rel res_loc], eax

    ; iResolution is constant — set once here, not per frame
    mov     edi, [rel res_loc]
    mov     eax, WIN_W
    cvtsi2ss xmm0, eax
    mov     eax, WIN_H
    cvtsi2ss xmm1, eax
    call    glUniform2f

    ; Record start time — iTime counts from this point
    mov     eax, SYS_CLOCK_GETTIME
    mov     edi, CLOCK_MONOTONIC
    lea     rsi, [rel cur_ts]
    syscall
    mov     rax, [rel cur_ts]
    mov     [rel start_sec], rax
    mov     rax, [rel cur_ts + 8]
    mov     [rel start_nsec], rax

    ret

; ── text_init ──────────────────────────────────────────────────────────────────
; Decompress the SDF text atlas and upload it as a GL_R8 texture on unit 0.
; Runs after shader_init: glShaderSource has copied the source string, so
; decomp_buf is free to reuse as the atlas destination. The sampler uniform
; uText defaults to 0 and GL_TEXTURE0 is the active unit — no glUniform1i.
text_init:
    ; uncompress(decomp_buf, &decomp_len, text_blob, text_blob_zlen)
    mov     qword [rel decomp_len], 512*1024
    lea     rdi, [rel decomp_buf]
    lea     rsi, [rel decomp_len]
    lea     rdx, [rel text_blob]
    mov     ecx, text_blob_zlen
    call    uncompress

    ; glGenTextures(1, &text_tex)
    mov     edi, 1
    lea     rsi, [rel text_tex]
    call    glGenTextures

    ; glBindTexture(GL_TEXTURE_2D, text_tex)
    mov     edi, GL_TEXTURE_2D
    mov     esi, [rel text_tex]
    call    glBindTexture

    ; glPixelStorei(GL_UNPACK_ALIGNMENT, 1) — atlas rows are not 4-byte padded
    mov     edi, GL_UNPACK_ALIGNMENT
    mov     esi, 1
    call    glPixelStorei

    ; glTexParameteri: LINEAR filtering (SDF wants smooth interpolation),
    ; CLAMP_TO_EDGE wrapping (atlas margin encodes "far outside")
    mov     edi, GL_TEXTURE_2D
    mov     esi, GL_TEXTURE_MIN_FILTER
    mov     edx, GL_LINEAR
    call    glTexParameteri

    mov     edi, GL_TEXTURE_2D
    mov     esi, GL_TEXTURE_MAG_FILTER
    mov     edx, GL_LINEAR
    call    glTexParameteri

    mov     edi, GL_TEXTURE_2D
    mov     esi, GL_TEXTURE_WRAP_S
    mov     edx, GL_CLAMP_TO_EDGE
    call    glTexParameteri

    mov     edi, GL_TEXTURE_2D
    mov     esi, GL_TEXTURE_WRAP_T
    mov     edx, GL_CLAMP_TO_EDGE
    call    glTexParameteri

    ; glTexImage2D(GL_TEXTURE_2D, 0, GL_R8, w, h, 0,
    ;              GL_RED, GL_UNSIGNED_BYTE, decomp_buf)
    ; Args 7-9 go on the stack; three qword pushes + one pad qword keeps
    ; rsp 16-byte aligned before the call (same pattern as XCreateSimpleWindow).
    mov     edi, GL_TEXTURE_2D
    xor     esi, esi                    ; level = 0
    mov     edx, GL_R8
    mov     ecx, text_atlas_w
    mov     r8d, text_atlas_h
    xor     r9d, r9d                    ; border = 0
    sub     rsp, 8                      ; alignment pad
    lea     rax, [rel decomp_buf]
    push    rax                         ; data             (arg 9)
    push    qword GL_UNSIGNED_BYTE      ; type             (arg 8)
    push    qword GL_RED                ; format           (arg 7)
    call    glTexImage2D
    add     rsp, 32

    ret

; ── audio_start ────────────────────────────────────────────────────────────────
audio_start:
    ; pthread_create(&audio_tid, NULL, audio_thread, NULL)
    lea     rdi, [rel audio_tid]
    xor     esi, esi
    lea     rdx, [rel audio_thread]
    xor     ecx, ecx
    call    pthread_create
    ret

; ── audio_thread ───────────────────────────────────────────────────────────────
audio_thread:
    ; Called in its own thread. rdi = arg (NULL, unused).
    ; TODO: snd_pcm_open(&pcm_handle, "default", SND_PCM_STREAM_PLAYBACK, 0)
    ; TODO: allocate hw_params, configure format/rate/channels, commit
    ; TODO: synthesis loop — oscillators + ADSR → PCM buffer → snd_pcm_writei
    xor     eax, eax            ; return NULL
    ret

; ── event_loop ─────────────────────────────────────────────────────────────────
event_loop:
.frame:
    ; glClear first — keeps xmm registers free for elapsed computation below
    mov     edi, GL_COLOR_BUFFER_BIT
    call    glClear

    ; elapsed = (cur_sec − start_sec) + (cur_nsec − start_nsec) × 1e-9
    ; Nanoseconds delta may be negative when the second rolls over; that is
    ; correct — the positive seconds delta compensates exactly.
    mov     eax, SYS_CLOCK_GETTIME
    mov     edi, CLOCK_MONOTONIC
    lea     rsi, [rel cur_ts]
    syscall

    mov     rax, [rel cur_ts]
    sub     rax, [rel start_sec]
    cvtsi2ss xmm0, rax                  ; whole-second delta as float

    mov     rax, [rel cur_ts + 8]
    sub     rax, [rel start_nsec]
    cvtsi2ss xmm2, rax
    mulss   xmm2, [rel f_ns_inv]        ; nanoseconds → fractional seconds
    addss   xmm0, xmm2                  ; xmm0 = iTime (elapsed seconds)

    ; glUniform1f(time_loc, elapsed) — xmm0 is the float arg per SysV ABI
    mov     edi, [rel time_loc]
    call    glUniform1f

    ; full-screen triangle — 3 vertices, positions from gl_VertexID in vert shader
    mov     edi, GL_TRIANGLES
    xor     esi, esi
    mov     edx, 3
    call    glDrawArrays

    mov     rdi, [rel display]
    mov     rsi, [rel window]
    call    glXSwapBuffers

    ; Drain all queued events without blocking, then render next frame.
.drain:
    mov     rdi, [rel display]
    call    XPending
    test    eax, eax
    jz      .frame              ; no events — go render

    mov     rdi, [rel display]
    lea     rsi, [rel xevent]
    call    XNextEvent

    mov     eax, [rel xevent]   ; event->type (first field)
    cmp     eax, DestroyNotify
    je      do_exit
    cmp     eax, ConfigureNotify
    je      .on_resize
    cmp     eax, KeyPress
    jne     .drain

    ; XLookupKeysym(&xevent, 0) — layout-agnostic keysym lookup
    lea     rdi, [rel xevent]
    xor     esi, esi
    call    XLookupKeysym
    cmp     rax, XK_Escape
    jne     .drain
    jmp     do_exit

.on_resize:
    ; XConfigureEvent: width at byte offset 56, height at 60.
    ; Update both viewport and iResolution so the shader sees the new dimensions.
    xor     edi, edi
    xor     esi, esi
    mov     edx, [rel xevent + 56]      ; new width
    mov     ecx, [rel xevent + 60]      ; new height
    call    glViewport

    mov     edi, [rel res_loc]
    mov     eax, [rel xevent + 56]
    cvtsi2ss xmm0, eax                  ; float width
    mov     eax, [rel xevent + 60]
    cvtsi2ss xmm1, eax                  ; float height
    call    glUniform2f

    jmp     .drain

; ── clean exit ─────────────────────────────────────────────────────────────────
do_exit:
    mov     eax, 60             ; sys_exit
    xor     edi, edi            ; status = 0
    syscall
