; about.asm — 8trax 4K intro
; x86-64 Linux, NASM, dynamic linking against libX11/libGL/libGLX/libz/libasound/libpthread
;
; Stack alignment convention:
;   `_start` does `sub rsp, 8` so every function we CALL enters with rsp%16 == 0.
;   Functions that make further calls need no additional alignment fixup — unless
;   they push an odd number of extra stack arguments before a call (see x11_open).

    bits 64

; ── X11 ────────────────────────────────────────────────────────────────────────
    extern XOpenDisplay
    extern XDefaultScreen
    extern XDefaultRootWindow
    extern XCreateSimpleWindow
    extern XSelectInput
    extern XMapWindow
    extern XMoveWindow
    extern XInternAtom
    extern XChangeProperty
    extern XNextEvent
    extern XPending
    extern XLookupKeysym
    extern XCloseDisplay

; ── GLX ────────────────────────────────────────────────────────────────────────
    extern glXChooseVisual
    extern glXCreateContext
    extern glXMakeCurrent
    extern glXSwapBuffers
    extern glXGetProcAddress

; ── zlib ───────────────────────────────────────────────────────────────────────
    extern uncompress

; ── ALSA ───────────────────────────────────────────────────────────────────────
    extern snd_pcm_open
    extern snd_pcm_hw_params_malloc
    extern snd_pcm_hw_params_any
    extern snd_pcm_hw_params_set_access
    extern snd_pcm_hw_params_set_format
    extern snd_pcm_hw_params_set_rate_near
    extern snd_pcm_hw_params_set_channels
    extern snd_pcm_hw_params
    extern snd_pcm_writei

; ── pthreads ───────────────────────────────────────────────────────────────────
    extern pthread_create

    global _start

; ── window geometry ────────────────────────────────────────────────────────────
WIN_W   equ 800
WIN_H   equ 600

; ── X11 event / mask constants ─────────────────────────────────────────────────
KeyPressMask        equ (1 << 0)
StructureNotifyMask equ (1 << 17)
KeyPress            equ 2
DestroyNotify       equ 17
XK_Escape           equ 0xff1b

; ── ALSA constants ─────────────────────────────────────────────────────────────
SND_PCM_STREAM_PLAYBACK       equ 0
SND_PCM_ACCESS_RW_INTERLEAVED equ 3
SND_PCM_FORMAT_S16_LE         equ 2
SAMPLE_RATE                   equ 44100

; ── GLX visual attribute list (terminated by None = 0) ─────────────────────────
; GLX_RGBA=4, GLX_DOUBLEBUFFER=5 are boolean flags (key only, no value).
; Remaining entries are key/value pairs.
%define GLX_RGBA            4
%define GLX_DOUBLEBUFFER    5
%define GLX_RED_SIZE        8
%define GLX_GREEN_SIZE      9
%define GLX_BLUE_SIZE       10

; ───────────────────────────────────────────────────────────────────────────────
section .rodata

; Compressed shader source — generated by: make shader_blob.inc
; Symbols defined: shader_blob_srclen (uncompressed), shader_blob_zlen, shader_blob
%include "shader_blob.inc"

; ───────────────────────────────────────────────────────────────────────────────
section .data

sz_display  db ":0", 0
sz_pcm      db "default", 0

glx_attr    dd GLX_RGBA, GLX_DOUBLEBUFFER
            dd GLX_RED_SIZE,   8
            dd GLX_GREEN_SIZE, 8
            dd GLX_BLUE_SIZE,  8
            dd 0                    ; None

; ───────────────────────────────────────────────────────────────────────────────
section .bss

display     resq 1              ; Display*
screen      resd 1              ; int
root        resq 1              ; Window  (root)
window      resq 1              ; Window  (ours)
glx_ctx     resq 1              ; GLXContext
vis_info    resq 1              ; XVisualInfo*
shader_prog resd 1              ; GLuint
time_loc    resd 1              ; GLint — iTime uniform location
res_loc     resd 1              ; GLint — iResolution uniform location
pcm_handle  resq 1              ; snd_pcm_t*
audio_tid   resq 1              ; pthread_t
xevent      resb 192            ; XEvent  (large enough for all subtypes)
decomp_buf  resb (64 * 1024)    ; shader source after zlib decompression
decomp_len  resq 1              ; decompressed byte count (for glShaderSource)

; ───────────────────────────────────────────────────────────────────────────────
section .text

; ── entry point ────────────────────────────────────────────────────────────────
_start:
    ; sub rsp, 8 shifts the stack so that every subsequent `call` delivers
    ; the callee with rsp%16 == 0 — the alignment library code expects.
    ; _start never returns; we exit via sys_exit.
    sub     rsp, 8

    call    x11_open
    call    glx_init
    call    shader_init
    call    audio_start
    call    event_loop

; ── x11_open ───────────────────────────────────────────────────────────────────
x11_open:
    ; XOpenDisplay(":0")
    lea     rdi, [rel sz_display]
    call    XOpenDisplay
    mov     [rel display], rax

    ; XDefaultScreen(display)
    mov     rdi, rax
    call    XDefaultScreen
    mov     [rel screen], eax

    ; XDefaultRootWindow(display)
    mov     rdi, [rel display]
    call    XDefaultRootWindow
    mov     [rel root], rax

    ; XCreateSimpleWindow(display, root, 0, 0, WIN_W, WIN_H, 0, 0, 0)
    ; Args 7-9 (border_width, border, background) go on the stack.
    ; Three qword pushes = 24 bytes; add one pad qword → 32 bytes total,
    ; keeping rsp 16-byte aligned before the call.
    mov     rdi, [rel display]
    mov     rsi, [rel root]
    xor     edx, edx            ; x = 0
    xor     ecx, ecx            ; y = 0
    mov     r8d, WIN_W
    mov     r9d, WIN_H
    sub     rsp, 8              ; alignment pad
    push    qword 0             ; background  (arg 9)
    push    qword 0             ; border      (arg 8)
    push    qword 0             ; border_width (arg 7)
    call    XCreateSimpleWindow
    add     rsp, 32
    mov     [rel window], rax

    ; XSelectInput(display, window, KeyPressMask | StructureNotifyMask)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    mov     edx, KeyPressMask | StructureNotifyMask
    call    XSelectInput

    ; TODO: suppress window decorations (_MOTIF_WM_HINTS or _NET_WM_WINDOW_TYPE_SPLASH)
    ; TODO: XMoveWindow to centre on screen after mapping

    ; XMapWindow(display, window)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    call    XMapWindow

    ret

; ── glx_init ───────────────────────────────────────────────────────────────────
glx_init:
    ; glXChooseVisual(display, screen, glx_attr)
    mov     rdi, [rel display]
    mov     esi, [rel screen]
    lea     rdx, [rel glx_attr]
    call    glXChooseVisual
    mov     [rel vis_info], rax

    ; glXCreateContext(display, vis_info, NULL, True)
    mov     rdi, [rel display]
    mov     rsi, [rel vis_info]
    xor     edx, edx            ; share_list = NULL
    mov     ecx, 1              ; direct = True
    call    glXCreateContext
    mov     [rel glx_ctx], rax

    ; glXMakeCurrent(display, window, ctx)
    mov     rdi, [rel display]
    mov     rsi, [rel window]
    mov     rdx, [rel glx_ctx]
    call    glXMakeCurrent

    ret

; ── shader_init ────────────────────────────────────────────────────────────────
shader_init:
    ; TODO: uncompress(decomp_buf, &decomp_len, shader_blob, shader_blob_zlen)
    ; TODO: resolve GL entry points via glXGetProcAddress
    ;         glCreateShader, glShaderSource, glCompileShader,
    ;         glCreateProgram, glAttachShader, glLinkProgram, glUseProgram,
    ;         glGetUniformLocation, glUniform1f, glUniform2f,
    ;         glCreateVertexArrays, glBindVertexArray, glDrawArrays
    ; TODO: create + compile fragment shader from decomp_buf
    ; TODO: create + link program; save to shader_prog
    ; TODO: glGetUniformLocation → time_loc, res_loc
    ret

; ── audio_start ────────────────────────────────────────────────────────────────
audio_start:
    ; pthread_create(&audio_tid, NULL, audio_thread, NULL)
    lea     rdi, [rel audio_tid]
    xor     esi, esi
    lea     rdx, [rel audio_thread]
    xor     ecx, ecx
    call    pthread_create
    ret

; ── audio_thread ───────────────────────────────────────────────────────────────
audio_thread:
    ; Called in its own thread. rdi = arg (NULL, unused).
    ; TODO: snd_pcm_open(&pcm_handle, "default", SND_PCM_STREAM_PLAYBACK, 0)
    ; TODO: allocate hw_params, configure format/rate/channels, commit
    ; TODO: synthesis loop — oscillators + ADSR → PCM buffer → snd_pcm_writei
    xor     eax, eax            ; return NULL
    ret

; ── event_loop ─────────────────────────────────────────────────────────────────
event_loop:
.frame:
    ; TODO: update iTime uniform (glUniform1f)
    ; TODO: glClear + glDrawArrays (full-screen quad via gl_VertexID trick)
    ; TODO: glXSwapBuffers

    ; Drain all queued events without blocking, then render next frame.
.drain:
    mov     rdi, [rel display]
    call    XPending
    test    eax, eax
    jz      .frame              ; no events — go render

    mov     rdi, [rel display]
    lea     rsi, [rel xevent]
    call    XNextEvent

    mov     eax, [rel xevent]   ; event->type (first field)
    cmp     eax, DestroyNotify
    je      do_exit
    cmp     eax, KeyPress
    jne     .drain

    ; XLookupKeysym(&xevent, 0) — layout-agnostic keysym lookup
    lea     rdi, [rel xevent]
    xor     esi, esi
    call    XLookupKeysym
    cmp     rax, XK_Escape
    jne     .drain

; ── clean exit ─────────────────────────────────────────────────────────────────
do_exit:
    mov     eax, 60             ; sys_exit
    xor     edi, edi            ; status = 0
    syscall
