#version 330 core

// Uniforms set each frame by about.asm
uniform float iTime;
uniform vec2  iResolution;

out vec4 fragColor;

// SDF text data generated by tools/mktext.py — spliced in by the Makefile
//@TEXT_DATA@

// ── Camera constants ───────────────────────────────────────────────────────────
// Ray = (uv.x, uv.y + PITCH, FOCAL); PITCH lifts the view so the whole frame is
// sky (horizon haze just kisses the bottom edge — no ground plane needed).
const float FOCAL = 1.4;
const float PITCH = 0.52;

// ── Hash / noise / fbm ─────────────────────────────────────────────────────────

float hash21(vec2 p) {
    p = fract(p * vec2(234.34, 435.345));
    p += dot(p, p + 34.23);
    return fract(p.x * p.y);
}

float vnoise(vec2 p) {
    vec2 i = floor(p), f = fract(p);
    vec2 u = f * f * (3.0 - 2.0 * f);
    float a = hash21(i);
    float b = hash21(i + vec2(1.0, 0.0));
    float c = hash21(i + vec2(0.0, 1.0));
    float d = hash21(i + vec2(1.0, 1.0));
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

const mat2 ROT = mat2(0.80, 0.60, -0.60, 0.80);

float fbm(vec2 p) {
    float v = 0.0, a = 0.5;
    for (int i = 0; i < 5; i++) {
        v += a * vnoise(p);
        p = ROT * p * 2.03;
        a *= 0.5;
    }
    return v;
}

// ── Cirrus clouds ──────────────────────────────────────────────────────────────
// Ray projected onto a high-altitude plane; anisotropic stretch + domain warp
// turns fbm blobs into elongated wisps. Returns coverage 0..1 (capped — cirrus
// are thin and never fully opaque).

float clouds(vec3 rd) {
    if (rd.y < 0.02) return 0.0;
    vec2 p = rd.xz / rd.y * 6.0;                    // plane projection (altitude folded into scale)
    p += vec2(iTime * 0.010, iTime * 0.003);        // wind drift
    p *= vec2(0.32, 1.0);                           // stretch → filaments elongated along x
    vec2 w = vec2(fbm(p * 1.7 + 11.3), fbm(p * 1.7 + 47.7));
    float d = fbm(p + (w - 0.5) * 1.8);             // domain warp → wispy strands
    d = smoothstep(0.60, 0.87, d);                  // sparse coverage
    d *= smoothstep(0.02, 0.20, rd.y);              // fade into horizon haze
    return d * 0.45;
}

// ── Sky dome ───────────────────────────────────────────────────────────────────
// Rayleigh-style elevation gradient + two-term Mie forward scatter
// (wide warm haze + tight bright core around the sun).

vec3 sky(vec3 rd, vec3 sun) {
    float sd   = clamp(dot(rd, sun), 0.0, 1.0);
    float elev = max(rd.y, 0.0);
    vec3 col = mix(vec3(0.66, 0.79, 0.93),          // horizon haze
                   vec3(0.05, 0.24, 0.70),          // zenith blue
                   pow(elev, 0.42));
    col += vec3(1.00, 0.80, 0.55) * 0.08 * pow(sd, 8.0);
    col += vec3(1.00, 0.90, 0.70) * 0.35 * pow(sd, 48.0);
    col += vec3(1.00, 0.95, 0.85) * 2.00 * pow(sd, 2000.0);  // hot halo hugging the disc
    return col;
}

// ── Lens flare ─────────────────────────────────────────────────────────────────
// Screen-space: chromatic ghosts along the sun→centre axis, a halo ring, and a
// faint anamorphic streak. Caller gates the whole thing by sun visibility.

vec3 flare(vec2 uv, vec2 s) {
    vec3 c = vec3(0.0);

    // anamorphic streak through the sun
    vec2 d = uv - s;
    c += vec3(0.30, 0.55, 1.00) * exp(-d.y * d.y * 900.0) * exp(-abs(d.x) * 3.5) * 0.55;

    // internal-reflection ghosts, mirrored through screen centre
    const float POS[6]  = float[6](-0.30, -0.55, -0.90, -1.25, -1.60, 0.45);
    const float RAD[6]  = float[6]( 0.028, 0.055, 0.090, 0.055, 0.110, 0.030);
    const vec3  TINT[6] = vec3[6](
        vec3(1.00, 0.60, 0.35), vec3(0.45, 0.80, 1.00), vec3(0.55, 1.00, 0.60),
        vec3(1.00, 0.45, 0.55), vec3(0.40, 0.55, 1.00), vec3(1.00, 0.85, 0.50));
    for (int i = 0; i < 6; i++) {
        float dd = length(uv - s * POS[i]);
        float blob = pow(max(1.0 - dd / RAD[i], 0.0), 2.2);
        c += TINT[i] * blob * 0.38;
    }

    // halo ring, offset opposite the sun
    float ring = abs(length(uv + s * 0.5) - 0.28);
    c += vec3(0.35, 0.55, 1.00) * exp(-ring * ring * 500.0) * 0.10;

    return c;
}

// ── Credit text ────────────────────────────────────────────────────────────────
// Blocks live in a single-channel SDF atlas texture uploaded by about.asm
// (0.5 = glyph edge, >0.5 inside). One channel gives anti-aliased fill +
// light rim at any scale, including the 10% corner watermark.

// uv is block-local [0,1]², v top-down. The canvas margin encodes "far
// outside", so clamping doubles as the out-of-bounds case.
float txSample(vec4 rect, vec2 uv) {
    return texture(uText, mix(rect.xy, rect.zw, clamp(uv, 0.0, 1.0))).r;
}

// Render one block: centre `c`, on-screen width `w`, rotation `ang`, squash
// (non-uniform jelly scale) `sq`, rubber-band `pull` (uv-space displacement of
// the block's bottom-left corner region); red8 = colour-split for block 1.
vec4 txBlock(vec2 uv, vec4 rect, int W, int H,
             vec2 c, float w, float ang, vec2 sq, vec2 pull, bool red8) {
    vec2 l = uv - c;
    float cs = cos(ang), sn = sin(ang);
    l = mat2(cs, -sn, sn, cs) * l;
    l /= sq;
    float h = w * float(H) / float(W);

    // Rubber-band warp: displacement weighted toward the bottom-left corner
    // (k=1 there, ~0.06 at the body's centre, 0 at top-right), so the pulled
    // corner stretches out while the body deforms but stays put. We render by
    // inverse mapping, so the forward warp is inverted by fixed-point iteration.
    vec2 q = l;
    for (int i = 0; i < 4; i++) {
        vec2 nl = q / vec2(w, h);
        float k = clamp(0.5 - nl.x, 0.0, 1.0) * clamp(0.5 - nl.y, 0.0, 1.0);
        q = l - pull * (k * k);
    }
    vec2 tuv = vec2(q.x / w + 0.5, 0.5 - q.y / h);

    float v = txSample(rect, tuv);
    float aa = 0.75 * length(vec2(dFdx(v), dFdy(v))) + 1e-4;
    float fill = smoothstep(0.5 - aa, 0.5 + aa, v);
    float rim  = smoothstep(0.42 - aa, 0.42 + aa, v);   // light rim around the fill

    vec3 fillCol = vec3(0.09, 0.09, 0.11);
    if (red8 && tuv.x < T1_SPLIT_U && tuv.y < T1_SPLIT_V)
        fillCol = vec3(0.76, 0.10, 0.09);

    return vec4(mix(vec3(1.0), fillCol, fill), rim);
}

// Drop from above with two bounces (second half the height of the first).
// Returns the vertical offset in uv units; +0.85 parks the block off-screen.
float dropY(float u) {
    const float D0 = 0.80, D1 = 0.55, D2 = 0.39;    // fall, bounce 1, bounce 2
    const float Y0 = 0.85, H1 = 0.16, H2 = 0.08;
    if (u < 0.0) return Y0;
    if (u < D0) { float s = u / D0; return Y0 * (1.0 - s * s); }
    u -= D0;
    if (u < D1) { float s = u / D1; return 4.0 * H1 * s * (1.0 - s); }
    u -= D1;
    if (u < D2) { float s = u / D2; return 4.0 * H2 * s * (1.0 - s); }
    return 0.0;
}

// ── Filmic tonemap (ACES fit) ──────────────────────────────────────────────────

vec3 aces(vec3 x) {
    return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

// ── Main ──────────────────────────────────────────────────────────────────────

void main() {
    vec2 uv = (gl_FragCoord.xy - 0.5 * iResolution) / iResolution.y;
    vec3 rd = normalize(vec3(uv.x, uv.y + PITCH, FOCAL));

    // Sun pans slowly back and forth across the view with a shallow
    // elevation drift; each traverse of the frame takes ~35 s.
    float az = 0.60 * sin(iTime * 0.09);
    float el = 0.30 + 0.06 * sin(iTime * 0.031);
    vec3 sun = normalize(vec3(sin(az) * cos(el), sin(el), cos(az) * cos(el)));

    // sky + HDR sun disc (soft limb; ~2° apparent diameter)
    vec3 col = sky(rd, sun);
    float sd = clamp(dot(rd, sun), 0.0, 1.0);
    col += vec3(1.00, 0.96, 0.90) * smoothstep(0.99965, 0.99990, sd) * 24.0;

    // clouds over sky+sun; brightened near the sun (silver lining)
    float cd = clouds(rd);
    // backlit cirrus must outshine the glow behind them, never silhouette it
    vec3 ccol = vec3(1.00, 1.00, 1.02) * (0.90 + 0.50 * pow(sd, 8.0) + 3.5 * pow(sd, 64.0));
    col = mix(col, ccol, cd);

    // lens flare — gated by sun in front of camera, inside frame, unoccluded
    if (sun.z > 0.02) {
        vec2 s = vec2(sun.x, sun.y) * (FOCAL / sun.z) - vec2(0.0, PITCH);
        float vis = (1.0 - smoothstep(0.55, 1.00, abs(s.x)))
                  * (1.0 - smoothstep(0.45, 0.85, abs(s.y)));
        vis *= clamp(1.0 - clouds(sun) * 1.2, 0.0, 1.0);
        col += flare(uv, s) * vis;
    }

    // grade: tonemap → gamma → saturation → vignette
    col = aces(col * 1.05);
    col = pow(col, vec3(1.0 / 2.2));
    col = mix(vec3(dot(col, vec3(0.299, 0.587, 0.114))), col, 1.12);
    col *= 1.0 - 0.14 * dot(uv, uv);

    // ── credit text choreography ─────────────────────────────────────────────
    float aspect = iResolution.x / iResolution.y;

    // block 1 — title: drop+bounce at 3 s, rest, then rubber-band to the
    // bottom-left corner at 8.2 s and live there for the whole demo (outside
    // the loop). Three phases: the corner is pulled and the body resists
    // (stretch), the tension wins and the block snaps down (snap, with a
    // slight overshoot), then the energy rings out in place (settle).
    vec2  c1 = vec2(0.0, dropY(iTime - 3.0));
    float w1 = 0.62, ang = 0.0;
    vec2  sq = vec2(1.0);
    vec2  pull = vec2(0.0);
    float uw = iTime - 8.2;
    if (uw > 0.0) {
        float wc = 0.62 * 0.50;                     // watermark: 50% of full size
        vec2 corner = vec2(-0.5 * aspect + 0.03 + 0.5 * wc,
                           -0.5 + 0.03 + 0.5 * wc * float(T1H) / float(T1W));
        const float TA = 1.2, TB = 0.30;            // stretch / snap durations
        if (uw < TA) {
            // corner creeps out toward its target; faint tension tremble
            float s = smoothstep(0.0, TA, uw);
            pull = corner * (0.32 * s * s * (1.0 + 0.05 * sin(uw * 34.0) * s));
        } else if (uw < TA + TB) {
            // released: back-ease-out overshoots the corner, band relaxes
            float e = (uw - TA) / TB;
            float b = 1.0 + 2.70158 * pow(e - 1.0, 3.0) + 1.70158 * pow(e - 1.0, 2.0);
            c1 = corner * b;
            w1 = mix(0.62, wc, e);
            pull = corner * (0.32 * (1.0 - e));
        } else {
            // ringing out: damped jelly in place
            float ts = uw - TA - TB;
            c1 = corner;
            w1 = wc;
            float damp = exp(-3.5 * ts);
            ang = 0.08 * sin(ts * 22.0) * damp;
            sq  = vec2(1.0 + 0.10 * sin(ts * 19.0) * damp,
                       1.0 - 0.10 * sin(ts * 19.0 + 0.8) * damp);
        }
    }
    vec4 t = txBlock(uv, T1RECT, T1W, T1H, c1, w1, ang, sq, pull, true);
    col = mix(col, t.rgb, t.a);

    // block 2 — placeholder: same drop+bounce at 11 s, rest, fly off right
    vec2 c2 = vec2(0.0, dropY(iTime - 11.0));
    float uf = iTime - 15.5;
    if (uf > 0.0) c2.x = 2.6 * uf * uf;
    t = txBlock(uv, T2RECT, T2W, T2H, c2, 0.80, 0.0, vec2(1.0), vec2(0.0), false);
    col = mix(col, t.rgb, t.a);

    // fade-in → dither
    col *= smoothstep(0.0, 2.5, iTime);
    col += (hash21(gl_FragCoord.xy + fract(iTime) * vec2(13.1, 7.7)) - 0.5) * (1.5 / 255.0);

    fragColor = vec4(col, 1.0);
}
