#!/usr/bin/env python3
"""Compress a GLSL shader with zlib and emit a NASM include file.

Usage: python3 tools/mkblob.py <shader.frag> <output.inc>

Symbols defined in output.inc:
    shader_blob_srclen  — uncompressed byte count (for uncompress() dest buffer)
    shader_blob_zlen    — compressed byte count   (for uncompress() src length)
    shader_blob         — label at the start of the compressed data bytes
"""

import sys
import zlib


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <shader.frag> <output.inc>")

    src_path, out_path = sys.argv[1], sys.argv[2]

    raw  = open(src_path, "rb").read()
    blob = zlib.compress(raw, level=9)

    lines = [
        "; auto-generated by tools/mkblob.py — do not edit",
        f"shader_blob_srclen  equ {len(raw)}",
        f"shader_blob_zlen    equ {len(blob)}",
        "shader_blob:",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i : i + 16]
        lines.append("    db " + ",".join(f"0x{b:02x}" for b in chunk))

    open(out_path, "w").write("\n".join(lines) + "\n")
    print(f"  shader: {len(raw)} B → {len(blob)} B compressed → {out_path}")


if __name__ == "__main__":
    main()
