name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install intro dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y nasm libx11-dev libgl-dev libasound2-dev zlib1g-dev
        printf '#!/bin/sh\nstrip "$@"\n' | sudo tee /usr/local/bin/sstrip
        sudo chmod +x /usr/local/bin/sstrip

    - name: Format check
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose
